<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 18 R Markdown | R and the Tidyverse: A Beginner’s Guide</title>
<meta name="author" content="Vivek H. Patil">
<meta name="description" content="Imagine you just finished a killer analysis—maybe you found the customer segment that’s bleeding money, or you built a model that predicts next quarter’s revenue. Now your boss says, “Great, put...">
<meta name="generator" content="bookdown 0.46 with bs4_book()">
<meta property="og:title" content="Chapter 18 R Markdown | R and the Tidyverse: A Beginner’s Guide">
<meta property="og:type" content="book">
<meta property="og:image" content="/cover.png">
<meta property="og:description" content="Imagine you just finished a killer analysis—maybe you found the customer segment that’s bleeding money, or you built a model that predicts next quarter’s revenue. Now your boss says, “Great, put...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 18 R Markdown | R and the Tidyverse: A Beginner’s Guide">
<meta name="twitter:description" content="Imagine you just finished a killer analysis—maybe you found the customer segment that’s bleeding money, or you built a model that predicts next quarter’s revenue. Now your boss says, “Great, put...">
<meta name="twitter:image" content="/cover.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.10.0/transition.js"></script><script src="libs/bs3compat-0.10.0/tabs.js"></script><script src="libs/bs3compat-0.10.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.34.0/datatables.js"></script><link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script><link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script><script src="libs/plotly-binding-4.12.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.25.2/plotly-latest.min.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet">
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script><link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet">
<script src="libs/selectize-0.12.0/selectize.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">R and the Tidyverse: A Beginner’s Guide</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="" href="introR.html"><span class="header-section-number">1</span> Introduction to R</a></li>
<li><a class="" href="Rgettingstarted.html"><span class="header-section-number">2</span> Getting Started with R</a></li>
<li><a class="" href="tidyverse.html"><span class="header-section-number">3</span> Your Data Analysis Toolkit</a></li>
<li><a class="" href="dataimport.html"><span class="header-section-number">4</span> Data Import</a></li>
<li><a class="" href="describedata.html"><span class="header-section-number">5</span> Describing Data</a></li>
<li><a class="" href="modifydata.html"><span class="header-section-number">6</span> Modifying Data</a></li>
<li><a class="" href="dplyr.html"><span class="header-section-number">7</span> Data Wrangling with dplyr</a></li>
<li><a class="" href="tidyr.html"><span class="header-section-number">8</span> Tidy Data with tidyr</a></li>
<li><a class="" href="summarystats.html"><span class="header-section-number">9</span> Summary Statistics</a></li>
<li><a class="" href="ggplot2basics.html"><span class="header-section-number">10</span> Data Visualization with ggplot2</a></li>
<li><a class="" href="ggplot2customize.html"><span class="header-section-number">11</span> Customizing ggplot2 Visualizations</a></li>
<li><a class="" href="singlevar.html"><span class="header-section-number">12</span> Single Variable Analysis</a></li>
<li><a class="" href="multivar.html"><span class="header-section-number">13</span> Relationships Between Variables</a></li>
<li><a class="" href="stringr.html"><span class="header-section-number">14</span> Working with Text Data</a></li>
<li><a class="" href="forcats.html"><span class="header-section-number">15</span> Wrangling Categories with forcats</a></li>
<li><a class="" href="lubridate.html"><span class="header-section-number">16</span> Working with Dates and Times</a></li>
<li><a class="" href="purrr.html"><span class="header-section-number">17</span> Doing the Same Thing to Many Things at Once</a></li>
<li><a class="active" href="rmarkdown.html"><span class="header-section-number">18</span> R Markdown</a></li>
<li><a class="" href="rmarkdown-advanced.html"><span class="header-section-number">19</span> Advanced R Markdown</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="rmarkdown" class="section level1" number="18">
<h1>
<span class="header-section-number">18</span> R Markdown<a class="anchor" aria-label="anchor" href="#rmarkdown"><i class="fas fa-link"></i></a>
</h1>
<p>Imagine you just finished a killer analysis—maybe you found the customer segment that’s bleeding money, or you built a model that predicts next quarter’s revenue. Now your boss says, “Great, put it in a report.”</p>
<p>So you do what everyone does: you run your code in R, copy-paste the numbers into Word, screenshot your charts, drag them into a slide deck, and pray that nothing changes before the meeting.</p>
<p>Then the data gets updated.</p>
<p>R Markdown exists so you never have to live that nightmare again. It lets you put your writing <em>and</em> your code in a single file. When you click one button, R runs everything and produces a polished HTML page, PDF, or Word doc—charts, tables, numbers, and all. If the data changes, you click the button again. Done.</p>
<p>This chapter will teach you everything you need to make professional-looking reports without suffering.</p>
<div id="what-is-rmarkdown" class="section level2" number="18.1">
<h2>
<span class="header-section-number">18.1</span> What is R Markdown?<a class="anchor" aria-label="anchor" href="#what-is-rmarkdown"><i class="fas fa-link"></i></a>
</h2>
<p>An R Markdown file (<code>.Rmd</code>) is basically a document where your words and your R code live together under one roof. When you <em>render</em> (or <em>knit</em>) it, three things happen:</p>
<ol style="list-style-type: decimal">
<li>R runs all your code.</li>
<li>It grabs the output—tables, charts, printed results.</li>
<li>It stitches everything together into a finished document.</li>
</ol>
<p>The result can be an HTML page, a PDF, a Word doc, slides, or even a full website (this book is written in R Markdown!). Think of it as a self-updating report.</p>
<p>You need two packages to make this work:</p>
<div class="sourceCode" id="cb447"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"rmarkdown"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"knitr"</span><span class="op">)</span></span></code></pre></div>
<p>That’s it. RStudio already has Pandoc (the engine that converts everything) built in, so you’re good to go.</p>
</div>
<div id="three-components" class="section level2" number="18.2">
<h2>
<span class="header-section-number">18.2</span> The Three Components of an R Markdown Document<a class="anchor" aria-label="anchor" href="#three-components"><i class="fas fa-link"></i></a>
</h2>
<p>Every <code>.Rmd</code> file has exactly three types of content:</p>
<ol style="list-style-type: decimal">
<li>
<strong>YAML header</strong> – The settings block at the top. Think of it as the “cover page setup.”</li>
<li>
<strong>Markdown text</strong> – Your actual writing: paragraphs, headers, bullet points.</li>
<li>
<strong>Code chunks</strong> – The R code that produces your numbers and charts.</li>
</ol>
<p>Here is the simplest R Markdown document you can write:</p>
<pre><code>---
title: "My First Report"
author: "Your Name"
date: "2024-01-15"
output: html_document
---

## Introduction

This is my first R Markdown document.

```{r}
summary(iris)
```</code></pre>
<p>Let’s break each piece down.</p>
</div>
<div id="yaml-header" class="section level2" number="18.3">
<h2>
<span class="header-section-number">18.3</span> YAML Header<a class="anchor" aria-label="anchor" href="#yaml-header"><i class="fas fa-link"></i></a>
</h2>
<p>The YAML header sits at the very top of your file, sandwiched between two lines of <code>---</code>. It tells R Markdown the basics: what’s this document called, who wrote it, and what format should the output be?</p>
<div id="the-essentials" class="section level3" number="18.3.1">
<h3>
<span class="header-section-number">18.3.1</span> The Essentials<a class="anchor" aria-label="anchor" href="#the-essentials"><i class="fas fa-link"></i></a>
</h3>
<p>Here is a perfectly good YAML header:</p>
<pre><code>---
title: "Quarterly Sales Report"
author: "Vivek H. Patil"
date: "2024-09-01"
output: html_document
---</code></pre>
<p>That’s really all you need. Four lines, and you’re in business.</p>
<p><strong>Pro tip:</strong> Want the date to update automatically every time you knit? Use this:</p>
<pre><code>date: "`r Sys.Date()`"</code></pre>
<p>Now your report always shows today’s date. No more “wait, is this the March version or the April version?”</p>
</div>
<div id="picking-your-output-format" class="section level3" number="18.3.2">
<h3>
<span class="header-section-number">18.3.2</span> Picking Your Output Format<a class="anchor" aria-label="anchor" href="#picking-your-output-format"><i class="fas fa-link"></i></a>
</h3>
<p>The three formats you’ll actually use:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Format</th>
<th align="left">YAML value</th>
<th align="left">When to use it</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">HTML</td>
<td align="left"><code>html_document</code></td>
<td align="left">Day-to-day reports, sharing via email</td>
</tr>
<tr class="even">
<td align="left">Word</td>
<td align="left"><code>word_document</code></td>
<td align="left">When your boss <em>needs</em> it in Word</td>
</tr>
<tr class="odd">
<td align="left">PDF</td>
<td align="left"><code>pdf_document</code></td>
<td align="left">Formal reports (requires LaTeX)</td>
</tr>
</tbody>
</table></div>
<p>HTML is the default, and honestly, it’s the best for most business use cases. It’s interactive, looks great, and you can email it as a single file.</p>
</div>
<div id="making-it-look-good" class="section level3" number="18.3.3">
<h3>
<span class="header-section-number">18.3.3</span> Making It Look Good<a class="anchor" aria-label="anchor" href="#making-it-look-good"><i class="fas fa-link"></i></a>
</h3>
<p>You can add a floating table of contents, pick a theme, and let readers show/hide code—all from the YAML header:</p>
<pre><code>---
title: "Sales Analysis Q3 2024"
author: "Vivek H. Patil"
date: "`r format(Sys.Date(), "%B %d, %Y")`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    code_folding: hide
---</code></pre>
<p>Here’s what each of those options does:</p>
<ul>
<li>
<strong><code>toc: true</code></strong> – Adds a table of contents (generated from your headers).</li>
<li>
<strong><code>toc_float: true</code></strong> – Makes the table of contents float on the side as you scroll. Very handy for long reports.</li>
<li>
<strong><code>theme</code></strong> – Changes the visual style. Try <code>cerulean</code>, <code>cosmo</code>, <code>flatly</code>, <code>journal</code>, <code>readable</code>, or <code>united</code>.</li>
<li>
<strong><code>code_folding: hide</code></strong> – Hides all code by default, but readers can click to reveal it. Perfect for reports where your manager doesn’t want to see code but your analyst colleague does.</li>
</ul>
<p>That’s really all the YAML you need to know. If you want to go deeper, Section <a href="rmarkdown.html#output-formats">18.7</a> has more detail.</p>
</div>
</div>
<div id="markdown-syntax" class="section level2" number="18.4">
<h2>
<span class="header-section-number">18.4</span> Markdown Syntax<a class="anchor" aria-label="anchor" href="#markdown-syntax"><i class="fas fa-link"></i></a>
</h2>
<p>The writing part of your document uses Markdown—a simple way to format text without messing around in a toolbar. If you’ve ever used Slack formatting or Reddit, you’ve basically used Markdown.</p>
<div id="headers" class="section level3" number="18.4.1">
<h3>
<span class="header-section-number">18.4.1</span> Headers<a class="anchor" aria-label="anchor" href="#headers"><i class="fas fa-link"></i></a>
</h3>
<p>Use <code>#</code> symbols to create headings. More <code>#</code> signs = smaller heading:</p>
<pre><code># Big Chapter Title
## Section
### Subsection</code></pre>
</div>
<div id="bold-italic-and-friends" class="section level3" number="18.4.2">
<h3>
<span class="header-section-number">18.4.2</span> Bold, Italic, and Friends<a class="anchor" aria-label="anchor" href="#bold-italic-and-friends"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>
<code>*italic*</code> gives you <em>italic</em>
</li>
<li>
<code>**bold**</code> gives you <strong>bold</strong>
</li>
<li>
<code>***bold italic***</code> gives you <strong><em>bold italic</em></strong>
</li>
<li>
<code>~~strikethrough~~</code> gives you <del>strikethrough</del>
</li>
</ul>
</div>
<div id="lists" class="section level3" number="18.4.3">
<h3>
<span class="header-section-number">18.4.3</span> Lists<a class="anchor" aria-label="anchor" href="#lists"><i class="fas fa-link"></i></a>
</h3>
<p>Bullet points:</p>
<pre><code>- Revenue grew 12%
- Costs decreased 3%
  - Labor costs down 5%
  - Materials costs up 2%
- Net profit up 15%</code></pre>
<p>Which renders as:</p>
<ul>
<li>Revenue grew 12%</li>
<li>Costs decreased 3%
<ul>
<li>Labor costs down 5%</li>
<li>Materials costs up 2%</li>
</ul>
</li>
<li>Net profit up 15%</li>
</ul>
<p>Numbered lists:</p>
<pre><code>1. Pull the data
2. Clean the data
3. Analyze the data
4. Pretend the data was clean all along</code></pre>
</div>
<div id="links" class="section level3" number="18.4.4">
<h3>
<span class="header-section-number">18.4.4</span> Links<a class="anchor" aria-label="anchor" href="#links"><i class="fas fa-link"></i></a>
</h3>
<pre><code>[The R Project](https://www.r-project.org/)</code></pre>
<p>Renders as: <a href="https://www.r-project.org/">The R Project</a></p>
</div>
<div id="tables" class="section level3" number="18.4.5">
<h3>
<span class="header-section-number">18.4.5</span> Tables<a class="anchor" aria-label="anchor" href="#tables"><i class="fas fa-link"></i></a>
</h3>
<p>You can type tables by hand using pipes and dashes:</p>
<pre><code>| Region  | Revenue | Growth |
|:--------|--------:|:------:|
| West    |    $45M |   12%  |
| East    |    $38M |    8%  |
| Central |    $29M |   -2%  |</code></pre>
<p>Renders as:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Region</th>
<th align="right">Revenue</th>
<th align="center">Growth</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">West</td>
<td align="right">$45M</td>
<td align="center">12%</td>
</tr>
<tr class="even">
<td align="left">East</td>
<td align="right">$38M</td>
<td align="center">8%</td>
</tr>
<tr class="odd">
<td align="left">Central</td>
<td align="right">$29M</td>
<td align="center">-2%</td>
</tr>
</tbody>
</table></div>
<p>The colons control alignment: <code>:---</code> is left, <code>---:</code> is right, <code>:---:</code> is centered.</p>
<p>For real data-driven tables, you’ll want to generate them from R—see Section <a href="rmarkdown.html#tables-in-rmarkdown">18.8</a>.</p>
</div>
<div id="blockquotes" class="section level3" number="18.4.6">
<h3>
<span class="header-section-number">18.4.6</span> Blockquotes<a class="anchor" aria-label="anchor" href="#blockquotes"><i class="fas fa-link"></i></a>
</h3>
<p>Prefix a line with <code>&gt;</code>:</p>
<pre><code>&gt; "Revenue is vanity, profit is sanity, cash is reality."</code></pre>
<p>Renders as:</p>
<blockquote>
<p>“Revenue is vanity, profit is sanity, cash is reality.”</p>
</blockquote>
</div>
<div id="math-equations" class="section level3" number="18.4.7">
<h3>
<span class="header-section-number">18.4.7</span> Math Equations<a class="anchor" aria-label="anchor" href="#math-equations"><i class="fas fa-link"></i></a>
</h3>
<p>Yes, you can write fancy equations if you need to. Most of you won’t need this often, but if you’re in a finance or econ class and your professor wants formulas, here’s the gist:</p>
<p>Inline math uses single dollar signs: <code>$\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i$</code> produces <span class="math inline">\(\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i\)</span>.</p>
<p>Display math uses double dollar signs:</p>
<p><span class="math display">\[
\hat{\beta} = (X^T X)^{-1} X^T y
\]</span></p>
<p>If you need more than that, Google “LaTeX math symbols” and you’ll find everything.</p>
</div>
</div>
<div id="code-chunks" class="section level2" number="18.5">
<h2>
<span class="header-section-number">18.5</span> Code Chunks<a class="anchor" aria-label="anchor" href="#code-chunks"><i class="fas fa-link"></i></a>
</h2>
<p>Code chunks are where the magic happens. This is the R code that actually does your analysis.</p>
<div id="inserting-a-code-chunk" class="section level3" number="18.5.1">
<h3>
<span class="header-section-number">18.5.1</span> Inserting a Code Chunk<a class="anchor" aria-label="anchor" href="#inserting-a-code-chunk"><i class="fas fa-link"></i></a>
</h3>
<p>A code chunk starts with <code>```{r}</code> and ends with <code>```</code>. The keyboard shortcut in RStudio is <strong>Ctrl+Alt+I</strong> (Windows) or <strong>Cmd+Option+I</strong> (Mac). Use it. Your fingers will thank you.</p>
<div class="sourceCode" id="cb458"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">)</span></span>
<span><span class="co">#&gt;                    mpg cyl disp  hp drat    wt  qsec vs am gear carb</span></span>
<span><span class="co">#&gt; Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4</span></span>
<span><span class="co">#&gt; Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4</span></span>
<span><span class="co">#&gt; Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1</span></span>
<span><span class="co">#&gt; Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1</span></span>
<span><span class="co">#&gt; Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2</span></span>
<span><span class="co">#&gt; Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</span></span></code></pre></div>
</div>
<div id="naming-your-chunks" class="section level3" number="18.5.2">
<h3>
<span class="header-section-number">18.5.2</span> Naming Your Chunks<a class="anchor" aria-label="anchor" href="#naming-your-chunks"><i class="fas fa-link"></i></a>
</h3>
<p>Give your chunks a name right after the <code>r</code>. It makes life easier when debugging (“Error in chunk <code>revenue-plot</code>” is way more helpful than “Error in unnamed-chunk-47”):</p>
<pre><code>```{r mpg-summary}
summary(mtcars$mpg)
```</code></pre>
<div class="sourceCode" id="cb460"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">$</span><span class="va">mpg</span><span class="op">)</span></span>
<span><span class="co">#&gt;    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. </span></span>
<span><span class="co">#&gt;   10.40   15.43   19.20   20.09   22.80   33.90</span></span></code></pre></div>
</div>
<div id="the-chunk-options-you-actually-need" class="section level3" number="18.5.3">
<h3>
<span class="header-section-number">18.5.3</span> The Chunk Options You Actually Need<a class="anchor" aria-label="anchor" href="#the-chunk-options-you-actually-need"><i class="fas fa-link"></i></a>
</h3>
<p>There are dozens of chunk options, but here are the ones that matter for 95% of business reports:</p>
<div id="showhide-code-and-output" class="section level4" number="18.5.3.1">
<h4>
<span class="header-section-number">18.5.3.1</span> Show/Hide Code and Output<a class="anchor" aria-label="anchor" href="#showhide-code-and-output"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="15%">
<col width="12%">
<col width="72%">
</colgroup>
<thead><tr class="header">
<th align="left">Option</th>
<th align="left">Default</th>
<th align="left">What it does</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code>echo</code></td>
<td align="left"><code>TRUE</code></td>
<td align="left">Show the code in the report?</td>
</tr>
<tr class="even">
<td align="left"><code>eval</code></td>
<td align="left"><code>TRUE</code></td>
<td align="left">Actually run the code?</td>
</tr>
<tr class="odd">
<td align="left"><code>include</code></td>
<td align="left"><code>TRUE</code></td>
<td align="left">Show <em>anything</em> (code + output) in the document?</td>
</tr>
</tbody>
</table></div>
<p><strong><code>echo=FALSE</code></strong> is your best friend for client-facing reports. It hides the code but shows the result:</p>
<pre><code>#&gt; [1] 20.09062</code></pre>
<p>The number above came from <code>mean(mtcars$mpg)</code>, but the code is hidden. Your VP doesn’t need to see R code. They need the answer.</p>
<p><strong><code>eval=FALSE</code></strong> shows code without running it. Good for “here’s how you would install this package” examples:</p>
<div class="sourceCode" id="cb462"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"tidyverse"</span><span class="op">)</span></span></code></pre></div>
<p><strong><code>include=FALSE</code></strong> runs the code silently—no code, no output in the report. Perfect for setup chunks where you load packages:</p>
<pre><code>```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
```</code></pre>
</div>
<div id="silencing-messages-and-warnings" class="section level4" number="18.5.3.2">
<h4>
<span class="header-section-number">18.5.3.2</span> Silencing Messages and Warnings<a class="anchor" aria-label="anchor" href="#silencing-messages-and-warnings"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="15%">
<col width="13%">
<col width="71%">
</colgroup>
<thead><tr class="header">
<th align="left">Option</th>
<th align="left">Default</th>
<th align="left">What it does</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code>message</code></td>
<td align="left"><code>TRUE</code></td>
<td align="left">Show messages (like package loading info)?</td>
</tr>
<tr class="even">
<td align="left"><code>warning</code></td>
<td align="left"><code>TRUE</code></td>
<td align="left">Show warnings?</td>
</tr>
</tbody>
</table></div>
<p>When you load packages, R loves to tell you about every attached namespace and masked function. Nobody reading your report cares:</p>
<div class="sourceCode" id="cb464"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span></code></pre></div>
<p>Set <code>message=FALSE</code> and <code>warning=FALSE</code> and enjoy the silence.</p>
</div>
<div id="controlling-figure-size" class="section level4" number="18.5.3.3">
<h4>
<span class="header-section-number">18.5.3.3</span> Controlling Figure Size<a class="anchor" aria-label="anchor" href="#controlling-figure-size"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="21%">
<col width="13%">
<col width="65%">
</colgroup>
<thead><tr class="header">
<th align="left">Option</th>
<th align="left">Default</th>
<th align="left">What it does</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code>fig.width</code></td>
<td align="left"><code>7</code></td>
<td align="left">Width in inches</td>
</tr>
<tr class="even">
<td align="left"><code>fig.height</code></td>
<td align="left"><code>5</code></td>
<td align="left">Height in inches</td>
</tr>
<tr class="odd">
<td align="left"><code>fig.cap</code></td>
<td align="left"><code>NULL</code></td>
<td align="left">Caption for the figure</td>
</tr>
<tr class="even">
<td align="left"><code>fig.align</code></td>
<td align="left"><code>"default"</code></td>
<td align="left">Alignment: <code>"left"</code>, <code>"center"</code>, <code>"right"</code>
</td>
</tr>
<tr class="odd">
<td align="left"><code>out.width</code></td>
<td align="left"><code>NULL</code></td>
<td align="left">Width in the output (e.g., <code>"80%"</code>)</td>
</tr>
</tbody>
</table></div>
<div class="sourceCode" id="cb465"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">iris</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Sepal.Length</span>, y <span class="op">=</span> <span class="va">Sepal.Width</span>, color <span class="op">=</span> <span class="va">Species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Iris: Sepal Dimensions"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Sepal Length (cm)"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Sepal Width (cm)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:iris-scatter"></span>
<img src="Rbook_files/figure-html/iris-scatter-1.png" alt="Scatter plot of sepal length versus sepal width, colored by species." width="576"><p class="caption">
Figure 18.1: Scatter plot of sepal length versus sepal width, colored by species.
</p>
</div>
</div>
</div>
<div id="global-chunk-options" class="section level3" number="18.5.4">
<h3>
<span class="header-section-number">18.5.4</span> Global Chunk Options<a class="anchor" aria-label="anchor" href="#global-chunk-options"><i class="fas fa-link"></i></a>
</h3>
<p>Tired of typing <code>message=FALSE, warning=FALSE</code> on every single chunk? Set defaults for the entire document in a setup chunk at the top:</p>
<pre><code>```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)
```</code></pre>
<p>Any individual chunk can still override these. Think of it like setting company-wide defaults, with each department free to customize.</p>
</div>
</div>
<div id="inline-r-code" class="section level2" number="18.6">
<h2>
<span class="header-section-number">18.6</span> Inline R Code<a class="anchor" aria-label="anchor" href="#inline-r-code"><i class="fas fa-link"></i></a>
</h2>
<p>This is one of the most underrated features of R Markdown. You can drop R results right into your sentences.</p>
<p>Instead of writing “the average MPG is 20.1” (and hoping you copied the right number), you write:</p>
<pre><code>The average MPG is `r round(mean(mtcars$mpg), 1)`.</code></pre>
<p>And it renders as: The average MPG is 20.1.</p>
<p>Here’s a more realistic example. Let’s say you computed some key numbers:</p>
<div class="sourceCode" id="cb468"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">avg_mpg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">$</span><span class="va">mpg</span><span class="op">)</span></span>
<span><span class="va">max_hp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">$</span><span class="va">hp</span><span class="op">)</span></span>
<span><span class="va">n_cyl6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">mtcars</span><span class="op">$</span><span class="va">cyl</span> <span class="op">==</span> <span class="fl">6</span><span class="op">)</span></span></code></pre></div>
<p>Now you can write sentences that update themselves:</p>
<ul>
<li>The average fuel efficiency across all cars is 20.1 miles per gallon.</li>
<li>The most powerful car has 335 horsepower.</li>
<li>There are 7 cars with 6 cylinders in the dataset.</li>
</ul>
<p>If the data changes, these numbers update automatically the next time you knit. No more copy-paste errors. No more “wait, did I update that number on slide 14?” This is the kind of thing that separates a good analyst from one who stays late fixing reports.</p>
</div>
<div id="output-formats" class="section level2" number="18.7">
<h2>
<span class="header-section-number">18.7</span> Output Formats in Detail<a class="anchor" aria-label="anchor" href="#output-formats"><i class="fas fa-link"></i></a>
</h2>
<div id="html-documents" class="section level3" number="18.7.1">
<h3>
<span class="header-section-number">18.7.1</span> HTML Documents<a class="anchor" aria-label="anchor" href="#html-documents"><i class="fas fa-link"></i></a>
</h3>
<p>HTML is the Swiss Army knife of output formats. Here’s a full-featured setup:</p>
<pre><code>---
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: flatly
    code_folding: hide
    df_print: paged
---</code></pre>
<ul>
<li>
<strong><code>df_print: paged</code></strong> – Makes data frames display as nice, paginated tables readers can click through. Way better than a wall of text.</li>
<li>
<strong><code>self_contained: true</code></strong> (the default) – Embeds everything into one HTML file. You can email it to anyone and it just works. No broken image links.</li>
</ul>
</div>
<div id="pdf-documents" class="section level3" number="18.7.2">
<h3>
<span class="header-section-number">18.7.2</span> PDF Documents<a class="anchor" aria-label="anchor" href="#pdf-documents"><i class="fas fa-link"></i></a>
</h3>
<p>PDF output looks polished and professional, but it needs a LaTeX installation. Easiest path:</p>
<div class="sourceCode" id="cb470"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"tinytex"</span><span class="op">)</span></span>
<span><span class="fu">tinytex</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/tinytex/man/install_tinytex.html">install_tinytex</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>Then in your YAML:</p>
<pre><code>---
output:
  pdf_document:
    toc: true
    number_sections: true
---</code></pre>
</div>
<div id="word-documents" class="section level3" number="18.7.3">
<h3>
<span class="header-section-number">18.7.3</span> Word Documents<a class="anchor" aria-label="anchor" href="#word-documents"><i class="fas fa-link"></i></a>
</h3>
<p>When your stakeholder absolutely, positively needs a <code>.docx</code>:</p>
<pre><code>---
output:
  word_document:
    toc: true
    reference_docx: my-styles.docx
---</code></pre>
<p>The <code>reference_docx</code> option is clever—you hand it a Word file with your company’s fonts and styles, and R Markdown applies them to the generated document. Brand guidelines? Handled.</p>
</div>
</div>
<div id="tables-in-rmarkdown" class="section level2" number="18.8">
<h2>
<span class="header-section-number">18.8</span> Tables in R Markdown<a class="anchor" aria-label="anchor" href="#tables-in-rmarkdown"><i class="fas fa-link"></i></a>
</h2>
<p>Hand-typing tables in Markdown is fine for small stuff, but for real data, let R build your tables.</p>
<div id="knitrkable" class="section level3" number="18.8.1">
<h3>
<span class="header-section-number">18.8.1</span> knitr::kable()<a class="anchor" aria-label="anchor" href="#knitrkable"><i class="fas fa-link"></i></a>
</h3>
<p>The simplest way to turn a data frame into a clean table:</p>
<div class="sourceCode" id="cb473"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">kable</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">iris</span><span class="op">)</span>, caption <span class="op">=</span> <span class="st">"First six rows of the iris dataset."</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:kable-basic">Table 18.1: </span>First six rows of the iris dataset.</caption>
<thead><tr class="header">
<th align="right">Sepal.Length</th>
<th align="right">Sepal.Width</th>
<th align="right">Petal.Length</th>
<th align="right">Petal.Width</th>
<th align="left">Species</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">5.1</td>
<td align="right">3.5</td>
<td align="right">1.4</td>
<td align="right">0.2</td>
<td align="left">setosa</td>
</tr>
<tr class="even">
<td align="right">4.9</td>
<td align="right">3.0</td>
<td align="right">1.4</td>
<td align="right">0.2</td>
<td align="left">setosa</td>
</tr>
<tr class="odd">
<td align="right">4.7</td>
<td align="right">3.2</td>
<td align="right">1.3</td>
<td align="right">0.2</td>
<td align="left">setosa</td>
</tr>
<tr class="even">
<td align="right">4.6</td>
<td align="right">3.1</td>
<td align="right">1.5</td>
<td align="right">0.2</td>
<td align="left">setosa</td>
</tr>
<tr class="odd">
<td align="right">5.0</td>
<td align="right">3.6</td>
<td align="right">1.4</td>
<td align="right">0.2</td>
<td align="left">setosa</td>
</tr>
<tr class="even">
<td align="right">5.4</td>
<td align="right">3.9</td>
<td align="right">1.7</td>
<td align="right">0.4</td>
<td align="left">setosa</td>
</tr>
</tbody>
</table></div>
<p>You can control column names, alignment, and decimal places:</p>
<div class="sourceCode" id="cb474"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mtcars_summary</span> <span class="op">&lt;-</span> <span class="va">mtcars</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">cyl</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span></span>
<span>    Count <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    Avg_MPG <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">mpg</span><span class="op">)</span>,</span>
<span>    Avg_HP <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">hp</span><span class="op">)</span>,</span>
<span>    Avg_WT <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">wt</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="fu">kable</span><span class="op">(</span><span class="va">mtcars_summary</span>,</span>
<span>      digits <span class="op">=</span> <span class="fl">2</span>,</span>
<span>      col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Cylinders"</span>, <span class="st">"Count"</span>, <span class="st">"Avg MPG"</span>, <span class="st">"Avg HP"</span>, <span class="st">"Avg Weight"</span><span class="op">)</span>,</span>
<span>      align <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span><span class="op">)</span>,</span>
<span>      caption <span class="op">=</span> <span class="st">"Summary statistics of mtcars by number of cylinders."</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:kable-formatted">Table 18.2: </span>Summary statistics of mtcars by number of cylinders.</caption>
<thead><tr class="header">
<th align="center">Cylinders</th>
<th align="center">Count</th>
<th align="right">Avg MPG</th>
<th align="right">Avg HP</th>
<th align="right">Avg Weight</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">4</td>
<td align="center">11</td>
<td align="right">26.66</td>
<td align="right">82.64</td>
<td align="right">2.29</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">7</td>
<td align="right">19.74</td>
<td align="right">122.29</td>
<td align="right">3.12</td>
</tr>
<tr class="odd">
<td align="center">8</td>
<td align="center">14</td>
<td align="right">15.10</td>
<td align="right">209.21</td>
<td align="right">4.00</td>
</tr>
</tbody>
</table></div>
</div>
<div id="kableextra-for-fancy-styling" class="section level3" number="18.8.2">
<h3>
<span class="header-section-number">18.8.2</span> kableExtra for Fancy Styling<a class="anchor" aria-label="anchor" href="#kableextra-for-fancy-styling"><i class="fas fa-link"></i></a>
</h3>
<p>Want boardroom-ready tables? The <code>kableExtra</code> package has you covered:</p>
<div class="sourceCode" id="cb475"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"kableExtra"</span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb476"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">mtcars_summary</span>,</span>
<span>      digits <span class="op">=</span> <span class="fl">2</span>,</span>
<span>      col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Cylinders"</span>, <span class="st">"Count"</span>, <span class="st">"Avg MPG"</span>, <span class="st">"Avg HP"</span>, <span class="st">"Avg Weight"</span><span class="op">)</span>,</span>
<span>      caption <span class="op">=</span> <span class="st">"Styled summary of mtcars by cylinder count."</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>bootstrap_options <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span><span class="op">)</span>,</span>
<span>                full_width <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>                position <span class="op">=</span> <span class="st">"center"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/column_spec.html">column_spec</a></span><span class="op">(</span><span class="fl">1</span>, bold <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold <span class="op">=</span> <span class="cn">TRUE</span>, color <span class="op">=</span> <span class="st">"white"</span>, background <span class="op">=</span> <span class="st">"#3366cc"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:kableextra-demo">Table 18.3: </span><span id="tab:kableextra-demo">Table 18.4: </span>Styled summary of mtcars by cylinder count.
</caption>
<thead><tr>
<th style="text-align:right;font-weight: bold;color: white !important;background-color: rgba(51, 102, 204, 255) !important;">
Cylinders
</th>
<th style="text-align:right;font-weight: bold;color: white !important;background-color: rgba(51, 102, 204, 255) !important;">
Count
</th>
<th style="text-align:right;font-weight: bold;color: white !important;background-color: rgba(51, 102, 204, 255) !important;">
Avg MPG
</th>
<th style="text-align:right;font-weight: bold;color: white !important;background-color: rgba(51, 102, 204, 255) !important;">
Avg HP
</th>
<th style="text-align:right;font-weight: bold;color: white !important;background-color: rgba(51, 102, 204, 255) !important;">
Avg Weight
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;">
4
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
26.66
</td>
<td style="text-align:right;">
82.64
</td>
<td style="text-align:right;">
2.29
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;">
6
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
19.74
</td>
<td style="text-align:right;">
122.29
</td>
<td style="text-align:right;">
3.12
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;">
8
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
15.10
</td>
<td style="text-align:right;">
209.21
</td>
<td style="text-align:right;">
4.00
</td>
</tr>
</tbody>
</table></div>
<p>Striped rows, hover effects, bold headers with a branded color—this is the kind of table that makes people think you spent way more time than you actually did.</p>
</div>
</div>
<div id="figures-and-images" class="section level2" number="18.9">
<h2>
<span class="header-section-number">18.9</span> Figures and Images<a class="anchor" aria-label="anchor" href="#figures-and-images"><i class="fas fa-link"></i></a>
</h2>
<div id="r-generated-plots" class="section level3" number="18.9.1">
<h3>
<span class="header-section-number">18.9.1</span> R-Generated Plots<a class="anchor" aria-label="anchor" href="#r-generated-plots"><i class="fas fa-link"></i></a>
</h3>
<p>Any code chunk that produces a plot automatically includes it in your document. Control the size and add a caption:</p>
<div class="sourceCode" id="cb477"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">mtcars</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cyl</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">mpg</span>, fill <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">cyl</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Number of Cylinders"</span>, y <span class="op">=</span> <span class="st">"Miles per Gallon"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_brewer.html">scale_fill_brewer</a></span><span class="op">(</span>palette <span class="op">=</span> <span class="st">"Set2"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:mtcars-boxplot"></span>
<img src="Rbook_files/figure-html/mtcars-boxplot-1.png" alt="Distribution of miles per gallon by number of cylinders." width="672"><p class="caption">
Figure 18.2: Distribution of miles per gallon by number of cylinders.
</p>
</div>
<p>Use <code>out.width</code> for percentage-based sizing, which usually works better than inches:</p>
<div class="sourceCode" id="cb478"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">iris</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Petal.Length</span>, fill <span class="op">=</span> <span class="va">Species</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Petal Length (cm)"</span>, y <span class="op">=</span> <span class="st">"Density"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:iris-density"></span>
<img src="Rbook_files/figure-html/iris-density-1.png" alt="Density plot of petal length by species." width="80%"><p class="caption">
Figure 18.3: Density plot of petal length by species.
</p>
</div>
</div>
<div id="side-by-side-plots" class="section level3" number="18.9.2">
<h3>
<span class="header-section-number">18.9.2</span> Side-by-Side Plots<a class="anchor" aria-label="anchor" href="#side-by-side-plots"><i class="fas fa-link"></i></a>
</h3>
<p>Want two charts next to each other? Use <code>fig.show="hold"</code> with <code>out.width="50%"</code>:</p>
<div class="sourceCode" id="cb479"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">mtcars</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">wt</span>, y <span class="op">=</span> <span class="va">mpg</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"MPG vs Weight"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">mtcars</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">hp</span>, y <span class="op">=</span> <span class="va">mpg</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"MPG vs Horsepower"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p><img src="Rbook_files/figure-html/side-by-side-plots-1.png" alt="" width="50%" style="display: block; margin: auto;"><img src="Rbook_files/figure-html/side-by-side-plots-2.png" alt="" width="50%" style="display: block; margin: auto;"></p>
</div>
<div id="external-images" class="section level3" number="18.9.3">
<h3>
<span class="header-section-number">18.9.3</span> External Images<a class="anchor" aria-label="anchor" href="#external-images"><i class="fas fa-link"></i></a>
</h3>
<p>To include an image file (like a company logo or a screenshot), use <code><a href="https://rdrr.io/pkg/knitr/man/include_graphics.html">knitr::include_graphics()</a></code> inside a code chunk:</p>
<div class="sourceCode" id="cb480"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/include_graphics.html">include_graphics</a></span><span class="op">(</span><span class="st">"https://www.r-project.org/Rlogo.png"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:r-logo"></span>
<img src="https://www.r-project.org/Rlogo.png" alt="The R Project logo." width="15%"><p class="caption">
Figure 18.4: The R Project logo.
</p>
</div>
</div>
</div>
<div id="cross-referencing" class="section level2" number="18.10">
<h2>
<span class="header-section-number">18.10</span> Cross-Referencing<a class="anchor" aria-label="anchor" href="#cross-referencing"><i class="fas fa-link"></i></a>
</h2>
<p>When your report gets longer than a few pages, you’ll want to say things like “as shown in Figure 3” or “see Table 2.” R Markdown (via bookdown) handles the numbering for you automatically.</p>
<div id="figures" class="section level3" number="18.10.1">
<h3>
<span class="header-section-number">18.10.1</span> Figures<a class="anchor" aria-label="anchor" href="#figures"><i class="fas fa-link"></i></a>
</h3>
<p>To cross-reference a figure, your chunk needs two things: a <strong>name</strong> and a <strong><code>fig.cap</code></strong>. Then use <code>\@ref(fig:chunk-name)</code> in your text. For example, <code>\@ref(fig:iris-scatter)</code> refers to Figure <a href="rmarkdown.html#fig:iris-scatter">18.1</a>.</p>
</div>
<div id="tables-1" class="section level3" number="18.10.2">
<h3>
<span class="header-section-number">18.10.2</span> Tables<a class="anchor" aria-label="anchor" href="#tables-1"><i class="fas fa-link"></i></a>
</h3>
<p>Same idea: <code>\@ref(tab:chunk-name)</code> where the chunk has a <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code> with a <code>caption</code>. Example: <code>\@ref(tab:kable-formatted)</code> refers to Table <a href="rmarkdown.html#tab:kable-formatted">18.2</a>.</p>
</div>
<div id="sections" class="section level3" number="18.10.3">
<h3>
<span class="header-section-number">18.10.3</span> Sections<a class="anchor" aria-label="anchor" href="#sections"><i class="fas fa-link"></i></a>
</h3>
<p>Give a section a label with <code>{#label}</code>, then reference it with <code>\@ref(label)</code>. The YAML header, for instance, is discussed in Section <a href="rmarkdown.html#yaml-header">18.3</a>.</p>
</div>
<div id="quick-reference-4" class="section level3" number="18.10.4">
<h3>
<span class="header-section-number">18.10.4</span> Quick Reference<a class="anchor" aria-label="anchor" href="#quick-reference-4"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="11%">
<col width="44%">
<col width="43%">
</colgroup>
<thead><tr class="header">
<th align="left">Element</th>
<th align="left">How to label it</th>
<th align="left">How to reference it</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Figure</td>
<td align="left">Chunk name + <code>fig.cap</code>
</td>
<td align="left"><code>\@ref(fig:chunk-name)</code></td>
</tr>
<tr class="even">
<td align="left">Table</td>
<td align="left">Chunk name + <code>kable(caption=...)</code>
</td>
<td align="left"><code>\@ref(tab:chunk-name)</code></td>
</tr>
<tr class="odd">
<td align="left">Section</td>
<td align="left"><code>## Title {#label}</code></td>
<td align="left"><code>\@ref(label)</code></td>
</tr>
</tbody>
</table></div>
</div>
</div>
<div id="citations-bibliography" class="section level2" number="18.11">
<h2>
<span class="header-section-number">18.11</span> Citations and Bibliography<a class="anchor" aria-label="anchor" href="#citations-bibliography"><i class="fas fa-link"></i></a>
</h2>
<p>If you’re writing a research paper or a thesis-style report, R Markdown handles citations. Add a <code>.bib</code> file to your YAML:</p>
<pre><code>---
bibliography: references.bib
link-citations: true
---</code></pre>
<p>Then cite with <code>@key</code> (in-text) or <code>[@key]</code> (parenthetical). The bibliography appears at the end automatically. If your professor or journal requires citations, this will save you hours compared to doing it by hand.</p>
</div>
<div id="rendering-documents" class="section level2" number="18.12">
<h2>
<span class="header-section-number">18.12</span> Rendering Documents<a class="anchor" aria-label="anchor" href="#rendering-documents"><i class="fas fa-link"></i></a>
</h2>
<div id="the-knit-button" class="section level3" number="18.12.1">
<h3>
<span class="header-section-number">18.12.1</span> The Knit Button<a class="anchor" aria-label="anchor" href="#the-knit-button"><i class="fas fa-link"></i></a>
</h3>
<p>Click <strong>Knit</strong> at the top of the RStudio editor. That’s it. Seriously.</p>
<p>The dropdown arrow next to it lets you pick the output format if you have more than one in your YAML.</p>
</div>
<div id="rmarkdownrender" class="section level3" number="18.12.2">
<h3>
<span class="header-section-number">18.12.2</span> rmarkdown::render()<a class="anchor" aria-label="anchor" href="#rmarkdownrender"><i class="fas fa-link"></i></a>
</h3>
<p>You can also render from the console, which is handy for automation:</p>
<div class="sourceCode" id="cb482"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">rmarkdown</span><span class="fu">::</span><span class="fu"><a href="https://pkgs.rstudio.com/rmarkdown/reference/render.html">render</a></span><span class="op">(</span><span class="st">"my-report.Rmd"</span><span class="op">)</span></span></code></pre></div>
<p>Override the output format:</p>
<div class="sourceCode" id="cb483"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">rmarkdown</span><span class="fu">::</span><span class="fu"><a href="https://pkgs.rstudio.com/rmarkdown/reference/render.html">render</a></span><span class="op">(</span><span class="st">"my-report.Rmd"</span>, output_format <span class="op">=</span> <span class="st">"pdf_document"</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="what-happens-under-the-hood" class="section level3" number="18.12.3">
<h3>
<span class="header-section-number">18.12.3</span> What Happens Under the Hood<a class="anchor" aria-label="anchor" href="#what-happens-under-the-hood"><i class="fas fa-link"></i></a>
</h3>
<p>When you click Knit:</p>
<ol style="list-style-type: decimal">
<li>
<strong>knitr</strong> runs all your code chunks and produces a plain Markdown (<code>.md</code>) file.</li>
<li>
<strong>Pandoc</strong> converts that <code>.md</code> file into your chosen output format.</li>
</ol>
<p>That’s the whole pipeline. If you get an error, it’s almost always in step 1 (your R code has a bug). Fix the code, knit again.</p>
</div>
</div>
<div id="tips-and-best-practices" class="section level2" number="18.13">
<h2>
<span class="header-section-number">18.13</span> Tips and Best Practices<a class="anchor" aria-label="anchor" href="#tips-and-best-practices"><i class="fas fa-link"></i></a>
</h2>
<div id="start-with-a-setup-chunk" class="section level3" number="18.13.1">
<h3>
<span class="header-section-number">18.13.1</span> Start with a Setup Chunk<a class="anchor" aria-label="anchor" href="#start-with-a-setup-chunk"><i class="fas fa-link"></i></a>
</h3>
<p>Every document should begin with a setup chunk that loads packages and sets defaults. Think of it as “opening the store before customers arrive”:</p>
<pre><code>```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center"
)
library(tidyverse)
library(knitr)
```</code></pre>
</div>
<div id="name-your-chunks" class="section level3" number="18.13.2">
<h3>
<span class="header-section-number">18.13.2</span> Name Your Chunks<a class="anchor" aria-label="anchor" href="#name-your-chunks"><i class="fas fa-link"></i></a>
</h3>
<p>“Error in unnamed-chunk-47” is about as helpful as a meeting that could have been an email. Name your chunks so you can actually find problems.</p>
</div>
<div id="use-echofalse-for-stakeholder-reports" class="section level3" number="18.13.3">
<h3>
<span class="header-section-number">18.13.3</span> Use <code>echo=FALSE</code> for Stakeholder Reports<a class="anchor" aria-label="anchor" href="#use-echofalse-for-stakeholder-reports"><i class="fas fa-link"></i></a>
</h3>
<p>Your CFO does not need to see <code><a href="https://dplyr.tidyverse.org">library(dplyr)</a></code>. Use <code>echo=FALSE</code> (or <code>code_folding: hide</code> in the YAML) to keep reports clean while preserving your code.</p>
</div>
<div id="use-parameterized-reports-for-repetitive-work" class="section level3" number="18.13.4">
<h3>
<span class="header-section-number">18.13.4</span> Use Parameterized Reports for Repetitive Work<a class="anchor" aria-label="anchor" href="#use-parameterized-reports-for-repetitive-work"><i class="fas fa-link"></i></a>
</h3>
<p>If you generate the same report for different regions, time periods, or product lines, use parameters:</p>
<pre><code>---
title: "Regional Sales Report"
params:
  region: "West"
  year: 2024
output: html_document
---</code></pre>
<p>Then in your code, use <code>params$region</code> and <code>params$year</code>. Render different versions like this:</p>
<div class="sourceCode" id="cb486"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">rmarkdown</span><span class="fu">::</span><span class="fu"><a href="https://pkgs.rstudio.com/rmarkdown/reference/render.html">render</a></span><span class="op">(</span><span class="st">"report.Rmd"</span>, params <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>region <span class="op">=</span> <span class="st">"East"</span>, year <span class="op">=</span> <span class="fl">2023</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>One template, infinite reports. Your future self will be grateful.</p>
</div>
<div id="keyboard-shortcuts-worth-memorizing" class="section level3" number="18.13.5">
<h3>
<span class="header-section-number">18.13.5</span> Keyboard Shortcuts Worth Memorizing<a class="anchor" aria-label="anchor" href="#keyboard-shortcuts-worth-memorizing"><i class="fas fa-link"></i></a>
</h3>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="30%">
<col width="30%">
<col width="38%">
</colgroup>
<thead><tr class="header">
<th align="left">Windows/Linux</th>
<th align="left">Mac</th>
<th align="left">What it does</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">Ctrl+Alt+I</td>
<td align="left">Cmd+Option+I</td>
<td align="left">Insert a new code chunk</td>
</tr>
<tr class="even">
<td align="left">Ctrl+Shift+K</td>
<td align="left">Cmd+Shift+K</td>
<td align="left">Knit the document</td>
</tr>
<tr class="odd">
<td align="left">Ctrl+Shift+Enter</td>
<td align="left">Cmd+Shift+Enter</td>
<td align="left">Run the current chunk</td>
</tr>
<tr class="even">
<td align="left">Ctrl+Enter</td>
<td align="left">Cmd+Enter</td>
<td align="left">Run the current line</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<div id="rmarkdown-summary" class="section level2" number="18.14">
<h2>
<span class="header-section-number">18.14</span> Summary<a class="anchor" aria-label="anchor" href="#rmarkdown-summary"><i class="fas fa-link"></i></a>
</h2>
<p>Here’s what you now know how to do:</p>
<ul>
<li>
<strong>Write a YAML header</strong> that sets up your document’s title, author, output format, and appearance.</li>
<li>
<strong>Use Markdown</strong> to format text with headers, bold, italic, lists, links, and tables.</li>
<li>
<strong>Write code chunks</strong> that run R code and control what shows up in the report with options like <code>echo</code>, <code>eval</code>, <code>message</code>, and <code>warning</code>.</li>
<li>
<strong>Use inline R code</strong> to drop computed numbers directly into your sentences (no more copy-paste errors).</li>
<li>
<strong>Generate tables</strong> with <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">knitr::kable()</a></code> and <code>kableExtra</code> that look presentation-ready.</li>
<li>
<strong>Include and size figures</strong> with chunk options like <code>fig.width</code>, <code>fig.height</code>, and <code>out.width</code>.</li>
<li>
<strong>Cross-reference</strong> figures, tables, and sections automatically.</li>
<li>
<strong>Render</strong> to HTML, PDF, or Word with one click.</li>
</ul>
<p>The bottom line: R Markdown turns your analysis into a self-updating, professional report. The more you use it, the more time you save—and the fewer “can you update the numbers?” emails you’ll get.</p>
<p>And remember, you can always access the R Markdown cheat sheet from RStudio via <strong>Help &gt; Cheat Sheets &gt; R Markdown Cheat Sheet</strong>.</p>
<p>One last thought. Reproducibility is not just a technical convenience — it is a form of intellectual honesty. When your analysis is transparent and re-runnable, anyone can check your work, challenge your assumptions, and build on what you did. In a world where data-driven decisions affect jobs, budgets, and opportunities, that kind of accountability is not optional. It is what professional integrity looks like in practice.</p>

</div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var sidebar = document.querySelector(".sidebar-book");
  if (!sidebar) return;

  // Create a slim tab on the left edge — visible, unobtrusive, clearly a toggle
  var btn = document.createElement("button");
  btn.innerHTML = '&#9776; Contents';
  btn.setAttribute("aria-label", "Toggle table of contents");
  btn.id = "sidebar-toggle-btn";
  document.body.appendChild(btn);

  var isOpen = false;

  function openSidebar() {
    isOpen = true;
    sidebar.classList.add("sidebar-open");
    btn.innerHTML = '&times; Close';
    btn.classList.add("sidebar-toggle-active");
  }

  function closeSidebar() {
    isOpen = false;
    sidebar.classList.remove("sidebar-open");
    btn.innerHTML = '&#9776; Contents';
    btn.classList.remove("sidebar-toggle-active");
  }

  btn.addEventListener("click", function(e) {
    e.stopPropagation();
    if (isOpen) { closeSidebar(); } else { openSidebar(); }
  });

  // Close when clicking outside
  document.addEventListener("click", function(e) {
    if (isOpen && !sidebar.contains(e.target) && e.target !== btn) {
      closeSidebar();
    }
  });

  // Close on Escape key
  document.addEventListener("keydown", function(e) {
    if (e.key === "Escape" && isOpen) { closeSidebar(); }
  });

  // Only activate on wide screens
  function checkWidth() {
    if (window.innerWidth >= 992) {
      btn.style.display = "flex";
      sidebar.classList.add("sidebar-collapsed");
    } else {
      btn.style.display = "none";
      sidebar.classList.remove("sidebar-collapsed");
      sidebar.classList.remove("sidebar-open");
    }
  }

  window.addEventListener("resize", checkWidth);
  checkWidth();
});
</script><div class="chapter-nav">
<div class="prev"><a href="purrr.html"><span class="header-section-number">17</span> Doing the Same Thing to Many Things at Once</a></div>
<div class="next"><a href="rmarkdown-advanced.html"><span class="header-section-number">19</span> Advanced R Markdown</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#rmarkdown"><span class="header-section-number">18</span> R Markdown</a></li>
<li><a class="nav-link" href="#what-is-rmarkdown"><span class="header-section-number">18.1</span> What is R Markdown?</a></li>
<li><a class="nav-link" href="#three-components"><span class="header-section-number">18.2</span> The Three Components of an R Markdown Document</a></li>
<li>
<a class="nav-link" href="#yaml-header"><span class="header-section-number">18.3</span> YAML Header</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-essentials"><span class="header-section-number">18.3.1</span> The Essentials</a></li>
<li><a class="nav-link" href="#picking-your-output-format"><span class="header-section-number">18.3.2</span> Picking Your Output Format</a></li>
<li><a class="nav-link" href="#making-it-look-good"><span class="header-section-number">18.3.3</span> Making It Look Good</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#markdown-syntax"><span class="header-section-number">18.4</span> Markdown Syntax</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#headers"><span class="header-section-number">18.4.1</span> Headers</a></li>
<li><a class="nav-link" href="#bold-italic-and-friends"><span class="header-section-number">18.4.2</span> Bold, Italic, and Friends</a></li>
<li><a class="nav-link" href="#lists"><span class="header-section-number">18.4.3</span> Lists</a></li>
<li><a class="nav-link" href="#links"><span class="header-section-number">18.4.4</span> Links</a></li>
<li><a class="nav-link" href="#tables"><span class="header-section-number">18.4.5</span> Tables</a></li>
<li><a class="nav-link" href="#blockquotes"><span class="header-section-number">18.4.6</span> Blockquotes</a></li>
<li><a class="nav-link" href="#math-equations"><span class="header-section-number">18.4.7</span> Math Equations</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#code-chunks"><span class="header-section-number">18.5</span> Code Chunks</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#inserting-a-code-chunk"><span class="header-section-number">18.5.1</span> Inserting a Code Chunk</a></li>
<li><a class="nav-link" href="#naming-your-chunks"><span class="header-section-number">18.5.2</span> Naming Your Chunks</a></li>
<li><a class="nav-link" href="#the-chunk-options-you-actually-need"><span class="header-section-number">18.5.3</span> The Chunk Options You Actually Need</a></li>
<li><a class="nav-link" href="#global-chunk-options"><span class="header-section-number">18.5.4</span> Global Chunk Options</a></li>
</ul>
</li>
<li><a class="nav-link" href="#inline-r-code"><span class="header-section-number">18.6</span> Inline R Code</a></li>
<li>
<a class="nav-link" href="#output-formats"><span class="header-section-number">18.7</span> Output Formats in Detail</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#html-documents"><span class="header-section-number">18.7.1</span> HTML Documents</a></li>
<li><a class="nav-link" href="#pdf-documents"><span class="header-section-number">18.7.2</span> PDF Documents</a></li>
<li><a class="nav-link" href="#word-documents"><span class="header-section-number">18.7.3</span> Word Documents</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#tables-in-rmarkdown"><span class="header-section-number">18.8</span> Tables in R Markdown</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#knitrkable"><span class="header-section-number">18.8.1</span> knitr::kable()</a></li>
<li><a class="nav-link" href="#kableextra-for-fancy-styling"><span class="header-section-number">18.8.2</span> kableExtra for Fancy Styling</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#figures-and-images"><span class="header-section-number">18.9</span> Figures and Images</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#r-generated-plots"><span class="header-section-number">18.9.1</span> R-Generated Plots</a></li>
<li><a class="nav-link" href="#side-by-side-plots"><span class="header-section-number">18.9.2</span> Side-by-Side Plots</a></li>
<li><a class="nav-link" href="#external-images"><span class="header-section-number">18.9.3</span> External Images</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#cross-referencing"><span class="header-section-number">18.10</span> Cross-Referencing</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#figures"><span class="header-section-number">18.10.1</span> Figures</a></li>
<li><a class="nav-link" href="#tables-1"><span class="header-section-number">18.10.2</span> Tables</a></li>
<li><a class="nav-link" href="#sections"><span class="header-section-number">18.10.3</span> Sections</a></li>
<li><a class="nav-link" href="#quick-reference-4"><span class="header-section-number">18.10.4</span> Quick Reference</a></li>
</ul>
</li>
<li><a class="nav-link" href="#citations-bibliography"><span class="header-section-number">18.11</span> Citations and Bibliography</a></li>
<li>
<a class="nav-link" href="#rendering-documents"><span class="header-section-number">18.12</span> Rendering Documents</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-knit-button"><span class="header-section-number">18.12.1</span> The Knit Button</a></li>
<li><a class="nav-link" href="#rmarkdownrender"><span class="header-section-number">18.12.2</span> rmarkdown::render()</a></li>
<li><a class="nav-link" href="#what-happens-under-the-hood"><span class="header-section-number">18.12.3</span> What Happens Under the Hood</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#tips-and-best-practices"><span class="header-section-number">18.13</span> Tips and Best Practices</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#start-with-a-setup-chunk"><span class="header-section-number">18.13.1</span> Start with a Setup Chunk</a></li>
<li><a class="nav-link" href="#name-your-chunks"><span class="header-section-number">18.13.2</span> Name Your Chunks</a></li>
<li><a class="nav-link" href="#use-echofalse-for-stakeholder-reports"><span class="header-section-number">18.13.3</span> Use echo=FALSE for Stakeholder Reports</a></li>
<li><a class="nav-link" href="#use-parameterized-reports-for-repetitive-work"><span class="header-section-number">18.13.4</span> Use Parameterized Reports for Repetitive Work</a></li>
<li><a class="nav-link" href="#keyboard-shortcuts-worth-memorizing"><span class="header-section-number">18.13.5</span> Keyboard Shortcuts Worth Memorizing</a></li>
</ul>
</li>
<li><a class="nav-link" href="#rmarkdown-summary"><span class="header-section-number">18.14</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>R and the Tidyverse: A Beginner’s Guide</strong>" was written by Vivek H. Patil. It was last built on 2026-02-27.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
